# 服务配置
server:
  port: 21090
  servlet:
    context-path: /itrs
# API地址前缀，用于接口拦截放行
my-server:
  api-context-path: /api/v1.0/itrs
#MySQL与文件上传限制配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名online-travel-db请根据自己本机实际创建的数据库进行修改。切记别把连接名当成数据库名！
    url: jdbc:mysql://localhost:3306/itrs?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: lihua
    # 改成自己root用户的密码
    password: 123456
# Mybatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  global-config:
    db-config:
      id-type: auto # 主键策略
  mapper-locations: classpath*:/mapper/**/*.xml # mapper文件位置




